name: Automatización

on:
  schedule:
    - cron: '* * * * *'   # Ejecutar cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Configurar R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.x'  # Cambia a la versión de R que necesites

    - name: Instalar dependencias
      run: |
        Rscript -e 'install.packages("httr")'
        Rscript -e 'install.packages("jsonlite")'
        Rscript -e 'install.packages("mongolite")'
        Rscript -e 'install.packages("tidyverse")'
        Rscript -e 'install.packages("lubridate")'

    - name: Ejecutar script R
      run: |
          Rscript scripts/1-testeo-inicial.R
          echo "Script ejecutado exitosamente"  
