name: Automatización

# on:
#   schedule:
#     - cron: '* * * * *'  # Ejecucion

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
      # with:
      #   r-version: '4.2' # The R version to download (if necessary) and use. 
        # Use "renv" to retrieve R version recorded in renv.lock file.
    #- run: 'scripts/1-testeo-inicial.R' -e 'print("Script main ejecutado exitosamente")'
    
    
    
    
    

    # steps:
    # - name: Checkout código
    #   uses: actions/checkout@v2
    # 
    # - name: Configurar R
    #   uses: r-lib/actions/setup-r@v2
    #   # with:
    #   #   r-version: '4.x' 
    # 
    # - name: Instalar dependencias
    #   run: |
    #     Rscript -e 'install.packages("httr")'
    #     Rscript -e 'install.packages("jsonlite")'
    #     Rscript -e 'install.packages("mongolite")'
    #     Rscript -e 'install.packages("tidyverse")'
    #     Rscript -e 'install.packages("lubridate")'
    # 
    - name: Ejecutar script R
      run: |
          Rscript scripts/1-testeo-inicial.R
          echo "Script main ejecutado exitosamente"
