name: Automatización

on:
  schedule:
    - cron: '* * * * *'  # Ejecucion

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Instalar R y dependencias
      run: |
        sudo apt-get update
        sudo apt-get install -y r-base
        Rscript -e 'install.packages(c("httr", "jsonlite", "mongolite", "tidyverse", "lubridate"))'

    - name: Ejecutar script R
      run: |
          Rscript scripts/1-testeo-inicial.R
          echo "Script main ejecutado exitosamente"  
